name: "install-crane"
description: "Installs crane"
inputs:
  version:
    description: version to install
    default: latest
    required: true
runs:
  using: "composite"
  steps:
  - name: Download crane
    id: download-crane
    run: |
      set -o errexit
      set -o nounset
      set -o pipefail

      version="${{ inputs.version }}"
      os="$(uname)"
      arch="$(arch)"

      if [[ "$version" == "latest" ]]; then
        version=$(curl -s https://api.github.com/repos/google/go-containerregistry/releases/latest | jq -r .tag_name)
      fi

      curl --fail -L https://github.com/google/go-containerregistry/releases/download/${version}/go-containerregistry_${os}_${arch}.tar.gz \
        | tar -xzf - crane
      mv crane /usr/bin/local
    shell: bash
    continue-on-error: true
  - name: Build crane, if unavailable to download
    if: steps.download-crane.outcome == 'failure'
    run: |
      set -o errexit
      set -o nounset
      set -o pipefail

      go install github.com/google/go-containerregistry/cmd/crane@${{ inputs.version }}
      cp $(go env GOPATH)/bin/crane /usr/local/bin
    shell: bash
    env:
      GOTOOLCHAIN: auto
  - name: crane version
    run: |
      set -o errexit
      set -o nounset
      set -o pipefail

      echo "installed to: $(which crane)"
      echo "crane version: $(crane version)"
    shell: bash