name: "install-crane"
description: "Installs crane"
inputs:
  version:
    description: crane version to install
    default: latest
    required: true
runs:
  using: "composite"
  steps:
  - name: Download crane
    id: download-crane
    run: |
      set -euo pipefail

      version="${{ inputs.version }}"
      os="$(uname)"
      arch="$(arch)"

      if [[ "${version}" == "latest" ]]; then
        version=$(curl -s https://api.github.com/repos/google/go-containerregistry/releases/latest | jq -r .tag_name)
      fi
      if [[ "${arch}" == "aarch64" ]]; then
        arch=arm64
      fi

      url="https://github.com/google/go-containerregistry/releases/download/${version}/go-containerregistry_${os}_${arch}.tar.gz"

      echo "Downloading ${url}"
      curl --fail -L "${url}" \
        | tar -xzf - crane
      mv crane /usr/local/bin
    shell: bash
    continue-on-error: true
  - name: Build crane, if unavailable to download
    if: steps.download-crane.outcome == 'failure'
    run: |
      set -euo pipefail

      go install github.com/google/go-containerregistry/cmd/crane@${{ inputs.version }}
      cp $(go env GOPATH)/bin/crane /usr/local/bin
    shell: bash
    env:
      GOTOOLCHAIN: auto
  - name: crane version
    run: |
      set -euo pipefail

      echo "installed to: $( which crane )"
      echo "crane version: $( crane version )"
    shell: bash