name: KinD cluster
description: Run a Kubernetes cluster in Docker
branding:
  icon: refresh-cw
  color: green
inputs:
  kind-version:
    description: Version of kind to use.
    type: string
  kubernetes-version:
    description: Version of Kubernetes to use. Resolves to a tag for the Kubernetes node image in the ghcr.io/scothis/kind/node repository. May also be specified as a fully qualified image.
    type: string
  registry:
    description: Custom local registry to trust for the cluster
    type: string
  registry-ca:
    description: Path to PEM encoded certificate authority to trust for the local registry
    type: string
runs:
  using: "composite"
  steps:
    - name: Resolve kind version
      id: kind-version
      run: |
        set -euo pipefail

        version="${{ inputs.kind-version }}"
        if [[ "${version}" == "" ]] ; then
          version="$(sed -n 's:require sigs.k8s.io/kind ::p' hack/kind/go.mod)"
        fi
        echo "version=${version}" >> "${GITHUB_OUTPUT}"
      shell: bash
    - name: Resolve kubernetes version
      id: kubernetes-version
      run: |
        set -euo pipefail

        version="${{ inputs.kubernetes-version }}"
        if [[ "${version}" == "" ]] ; then
          version="$(sed -n 's:require k8s.io/kubectl ::p' hack/kubernetes/go.mod | sed s/^v0\./v1\./)"
        fi
        # will fail if there's a node image in the library
        if [[ ! "${version}" =~ [/:@] ]] ; then
          version="ghcr.io/scothis/kind/node:${version}"
        fi
        echo "version=${version}" >> "${GITHUB_OUTPUT}"
      shell: bash
    - name: Install kind
      uses: ./.github/actions/install-kind
      with:
        version: ${{ steps.kind-version.outputs.version }}
    - name: Cluster
      uses: ./.github/actions/with-post-step
      with:
        main: ${{ github.action_path }}/scripts/start-cluster.sh "kind" "${{ steps.kubernetes-version.outputs.version }}" "${{ inputs.registry }}" "${{ inputs.registry-ca }}"
        post: ${{ github.action_path }}/scripts/stop-cluster.sh "kind"
