name: KinD cluster
description: Run a Kubernetes cluster in Docker
branding:
  icon: refresh-cw
  color: green
inputs:
  kind-version:
    description: Version of kind to use.
    type: string
  kubernetes-version:
    description: Version of Kubernetes to use. Resolves to a tag for the Kubernetes node image in the ghcr.io/scothis/kind/node repository. May also be specified as a fully qualified image.
    type: string
runs:
  using: "composite"
  steps:
    - name: Resolve kind version
      id: kind-version
      run: |
        set -euo pipefail

        version="${{ inputs.kind-version }}"
        if [[ "${version}" == "" ]] ; then
          version="$(sed -n 's:require sigs.k8s.io/kind ::p' hack/kind/go.mod)"
        fi
        echo "version=${version}" >> "${GITHUB_OUTPUT}"
      shell: bash
    - name: Resolve kubernetes version
      id: kubernetes-version
      run: |
        set -euo pipefail

        version="${{ inputs.kubernetes-version }}"
        if [[ "${version}" == "" ]] ; then
          version=":$(sed -n 's:require k8s.io/kubectl ::p' hack/kubernetes/go.mod | sed s/^v0\./v1\./)"
        fi
        # will fail if there's a node image in the library
        if [[ ! "${version}" =~ [/:@] ]] ; then
          version="ghcr.io/scothis/kind/node:${version}"
        fi
        echo "version=${version}" >> "${GITHUB_OUTPUT}"
      shell: bash
    - name: Install kind
      uses: ./.github/actions/install-kind
      with:
        version: ${{ steps.kind-version.outputs.version }}
    - name: Cluster
      uses: ./.github/actions/with-post-step
      with:
        main: kind create cluster --image "${{ steps.kubernetes-version.outputs.version }}"
        post: kind delete cluster
