name: Dependabot auto-merge

on:
  push:
    branches:
    - 'dependabot/go_modules/versions/kubernetes/v**'

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && github.repository == 'reconcilerio/kind'
    steps:
      - name: Set PR to auto-merge
        run: gh pr merge --auto --squash ${{ github.ref_name }}
        env:
          # since new GitHub Action workflows are not triggered by existing workflows,
          # use custom PAT so the resulting merge commit triggers the push workflow
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
