name: Push

on:
  push:
    branches:
    - '**'
    - '!dependabot/**'

jobs:

  preflight:
    name: Preflight
    runs-on: ubuntu-latest
    outputs:
      kind-version: ${{ steps.kind.outputs.version }}
      kubernetes: ${{ steps.kubernetes.outputs.version }}
      kubernetes-1.37: ${{ steps.kubernetes.outputs['1.37'] }}
      kubernetes-1.36: ${{ steps.kubernetes.outputs['1.36'] }}
      kubernetes-1.35: ${{ steps.kubernetes.outputs['1.35'] }}
      kubernetes-1.34: ${{ steps.kubernetes.outputs['1.34'] }}
      kubernetes-1.33: ${{ steps.kubernetes.outputs['1.33'] }}
    steps:
    - uses: actions/checkout@v6
    
    - name: Resolve kind version
      id: kind
      run: echo "version=$(go list -modfile hack/kind/go.mod -m -f '{{.Version}}' sigs.k8s.io/kind)" | tee -a "${GITHUB_OUTPUT}"
      env:
        GOTOOLCHAIN: auto
    - name: Resolve kubernetes version
      id: kubernetes
      run: |
        set -euo pipefail

        echo "version=$(go list -modfile hack/kubernetes/go.mod -m -f '{{.Version}}' k8s.io/kubectl | sed s/^v0\./v1\./)" | tee -a "${GITHUB_OUTPUT}"
        echo "1.37=$(go list -modfile hack/kubernetes-1.37/go.mod -m -f '{{.Version}}' k8s.io/kubectl | sed s/^v0\./v1\./)" | tee -a "${GITHUB_OUTPUT}"
        echo "1.36=$(go list -modfile hack/kubernetes-1.36/go.mod -m -f '{{.Version}}' k8s.io/kubectl | sed s/^v0\./v1\./)" | tee -a "${GITHUB_OUTPUT}"
        echo "1.35=$(go list -modfile hack/kubernetes-1.35/go.mod -m -f '{{.Version}}' k8s.io/kubectl | sed s/^v0\./v1\./)" | tee -a "${GITHUB_OUTPUT}"
        echo "1.34=$(go list -modfile hack/kubernetes-1.34/go.mod -m -f '{{.Version}}' k8s.io/kubectl | sed s/^v0\./v1\./)" | tee -a "${GITHUB_OUTPUT}"
        echo "1.33=$(go list -modfile hack/kubernetes-1.33/go.mod -m -f '{{.Version}}' k8s.io/kubectl | sed s/^v0\./v1\./)" | tee -a "${GITHUB_OUTPUT}"
      env:
        GOTOOLCHAIN: auto

  base:
    name: Base image
    needs: preflight
    permissions:
      packages: write
      id-token: write
    uses: ./.github/workflows/image-base.yaml
    with:
      kind-version: ${{ needs.preflight.outputs.kind-version }}
      tag: ${{ needs.preflight.outputs.kind-version }}
      publish: ${{ github.ref == 'refs/heads/main' }}
    secrets: inherit

  node:
    name: Node image
    permissions:
      packages: write
      id-token: write
    needs: [base, preflight]
    strategy:
      fail-fast: false
      matrix:
        include:
        - kubernetes-version: ${{ needs.preflight.outputs['kubernetes'] }}
          tag: ${{ needs.preflight.outputs['kubernetes'] }}-${{ needs.preflight.outputs.kind-version }}
        - kubernetes-version: ${{ needs.preflight.outputs['kubernetes-1.37'] }}
          tag: ${{ needs.preflight.outputs['kubernetes-1.37'] }}-${{ needs.preflight.outputs.kind-version }}
          additional-tags: |
            ${{ needs.preflight.outputs['kubernetes-1.37'] }}
            v1.37
        - kubernetes-version: ${{ needs.preflight.outputs['kubernetes-1.36'] }}
          tag: ${{ needs.preflight.outputs['kubernetes-1.36'] }}-${{ needs.preflight.outputs.kind-version }}
          additional-tags: |
            ${{ needs.preflight.outputs['kubernetes-1.36'] }}
            v1.36
        - kubernetes-version: ${{ needs.preflight.outputs['kubernetes-1.35'] }}
          tag: ${{ needs.preflight.outputs['kubernetes-1.35'] }}-${{ needs.preflight.outputs.kind-version }}
          additional-tags: |
            ${{ needs.preflight.outputs['kubernetes-1.35'] }}
            v1.35
        - kubernetes-version: ${{ needs.preflight.outputs['kubernetes-1.34'] }}
          tag: ${{ needs.preflight.outputs['kubernetes-1.34'] }}-${{ needs.preflight.outputs.kind-version }}
          additional-tags: |
            ${{ needs.preflight.outputs['kubernetes-1.34'] }}
            v1.34
        - kubernetes-version: ${{ needs.preflight.outputs['kubernetes-1.33'] }}
          tag: ${{ needs.preflight.outputs['kubernetes-1.33'] }}-${{ needs.preflight.outputs.kind-version }}
          additional-tags: |
            ${{ needs.preflight.outputs['kubernetes-1.33'] }}
            v1.33
    uses: ./.github/workflows/image-node.yaml
    with:
      kind-version: "${{ needs.preflight.outputs.kind-version }}"
      kind-base-artifact-name: "${{ needs.base.outputs.artifact-name }}"
      kind-base-digest: "${{ needs.base.outputs.digest }}"
      kubernetes-version: "${{ matrix.kubernetes-version }}"
      tag: "${{ matrix.tag }}"
      additional-tags: "${{ matrix.additional-tags }}"
      publish: ${{ github.ref == 'refs/heads/main' }}
      id: "${{ github.run_id }}-${{ strategy.job-index }}"
    secrets: inherit

  done:
    name: Done
    needs: [node, preflight]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v6
    - name: Install crane
      uses: reconcilerio/install-crane-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Latest tag
      run: |
        crane tag \
          "ghcr.io/${{ github.repository }}/node:${{ needs.preflight.outputs['kubernetes'] }}-${{ needs.preflight.outputs.kind-version }}" \
          "latest"
    - run: echo "That's all folks"
