name: Test

on:
  push:
    branches:
    - '**'
    - '!dependabot/**'
    tags:
    # semver tags
    - 'v[0-9]+\.[0-9]+\.[0-9]+-?**'
  pull_request: {}

env:
  kind-version: v0.31.0
  kubernetes-version: v1.36.0
  ggcr-version: v0.21.5

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout kind ${{ env.kind-version }}
      uses: actions/checkout@v6
      with:
        repository: kubernetes-sigs/kind
        path: kind
        ref: ${{ env.kind-version }}
    - name: Checkout kubernetes ${{ env.kubernetes-version }}
      uses: actions/checkout@v6
      with:
        repository: kubernetes/kubernetes
        path: kubernetes
        ref: ${{ env.kubernetes-version }}
    - name: Checkout ggcr ${{ env.ggcr-version }}
      uses: actions/checkout@v6
      with:
        repository: google/go-containerregistry
        path: ggcr
        ref: ${{ env.ggcr-version }}
    - uses: actions/setup-go@v6
      with:
        go-version-file: ./kind/.go-version
        cache-dependency-path: '**/go.sum'
    - name: Build kind
      run: go build . && mv kind /usr/local/bin
      working-directory: kind
    - name: Build crane
      run: go build ./cmd/crane && mv crane /usr/local/bin
      working-directory: ggcr

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Check for existing base image
      id: base_image_check
      run: crane digest ghcr.io/${{ github.repository }}/base:${{ env.kind-version }}
      continue-on-error: true
    - name: Build kind base image
      if: steps.base_image_check.outcome == 'failure'
      run: make push
      env:
        IMAGE: ghcr.io/${{ github.repository }}/base:${{ env.kind-version }}
      working-directory: kind/images/base
    
    - name: Check for existing amd64 node image
      id: node_amd64_image_check
      run: crane digest ghcr.io/${{ github.repository }}/node/amd64:${{ env.kubernetes-version }}-${{ env.kind-version }}
      continue-on-error: true
    - name: Build kind amd64 node image
      if: steps.node_amd64_image_check.outcome == 'failure'
      run: |
        kind build node-image ./kubernetes \
          --arch linux/amd64 \
          --base-image ghcr.io/${{ github.repository }}/base:${{ env.kind-version }} \
          --image ghcr.io/${{ github.repository }}/node/amd64:${{ env.kubernetes-version }}-${{ env.kind-version }} \
          --type release

    - name: Check for existing arm64 node image
      id: node_arm64_image_check
      run: crane digest ghcr.io/${{ github.repository }}/node/arm64:${{ env.kubernetes-version }}-${{ env.kind-version }}
      continue-on-error: true
    - name: Build kind arm64 node image
      if: steps.node_arm64_image_check.outcome == 'failure'
      run: |
        kind build node-image ./kubernetes \
          --arch linux/arm64 \
          --base-image ghcr.io/${{ github.repository }}/base:${{ env.kind-version }} \
          --image ghcr.io/${{ github.repository }}/node/arm64:${{ env.kubernetes-version }}-${{ env.kind-version }} \
          --type release
    
    - name: Check for existing node image
      id: node_image_check
      run: crane digest ghcr.io/${{ github.repository }}/node:${{ env.kubernetes-version }}-${{ env.kind-version }}
      continue-on-error: true
    - name: Assemble kind node image
      if: steps.node_image_check.outcome == 'failure'
      run: |
        crane index append \
          -m ghcr.io/${{ github.repository }}/node/amd64:${{ env.kubernetes-version }}-${{ env.kind-version }} \
          -m ghcr.io/${{ github.repository }}/node/arm64:${{ env.kubernetes-version }}-${{ env.kind-version }} \
          -t ghcr.io/${{ github.repository }}/node:${{ env.kubernetes-version }}-${{ env.kind-version }}

    - name: Vanity tags
      run: |
        crane tag ghcr.io/${{ github.repository }}/node:${{ env.kubernetes-version }}-${{ env.kind-version }} ghcr.io/${{ github.repository }}/node:${{ env.kubernetes-version }}
        crane tag ghcr.io/${{ github.repository }}/node:${{ env.kubernetes-version }}-${{ env.kind-version }} ghcr.io/${{ github.repository }}/node:$( ${kubernetes-version} | cut -d'.' -f1-2 )
