name: Test

on:
  push:
    branches:
    - '**'
    - '!dependabot/**'
    tags:
    # semver tags
    - 'v[0-9]+\.[0-9]+\.[0-9]+-?**'
  pull_request: {}

env:
  kind-version: v0.31.0
  cloud-provider-kind-version: v0.10.0
  kubernetes-version: v1.36.0
  ggcr-version: v0.21.5

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout kind ${{ env.kind-version }}
      uses: actions/checkout@v6
      with:
        repository: kubernetes-sigs/kind
        path: kind
        ref: ${{ env.kind-version }}
    - name: Checkout cloud-provider-kind ${{ env.cloud-provider-kind-version }}
      uses: actions/checkout@v6
      with:
        repository: kubernetes-sigs/cloud-provider-kind
        path: cloud-provider-kind
        ref: ${{ env.cloud-provider-kind-version }}
    - name: Checkout kubernetes ${{ env.kubernetes-version }}
      uses: actions/checkout@v6
      with:
        repository: kubernetes/kubernetes
        path: kubernetes
        ref: ${{ env.kubernetes-version }}
    - name: Checkout ggcr ${{ env.ggcr-version }}
      uses: actions/checkout@v6
      with:
        repository: google/go-containerregistry
        path: ggcr
        ref: ${{ env.ggcr-version }}
    - uses: actions/setup-go@v6
      with:
        go-version-file: ./kind/.go-version
        cache-dependency-path: '**/go.sum'
    - name: Build kind
      run: go build . && mv kind /usr/local/bin
      working-directory: kind
    - name: Build cloud-provider-kind
      run: go build . && mv cloud-provider-kind /usr/local/bin
      working-directory: cloud-provider-kind
    - name: Build crane
      run: go build ./cmd/crane && mv crane /usr/local/bin
      working-directory: ggcr

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Check for existing base-image
      id: base_image_check
      run: crane digest ghcr.io/${{ github.repository }}/base:${{ env.kind-version }}
      continue-on-error: true
    - name: Build kind base-image
      if: steps.base_image_check.outcome == 'failure'
      run: make push
      env:
        IMAGE: ghcr.io/${{ github.repository }}/base:${{ env.kind-version }}
      working-directory: kind/images/base
    - name: Build kind node-image amd64
      run: kind build node-image ./kubernetes --arch linux/amd64 --base-image ghcr.io/${{ github.repository }}/base:${{ env.kind-version }} --image ghcr.io/${{ github.repository }}/node/amd64:${{ env.kubernetes-version }} --release
    - name: Build kind node-image arm64
      run: kind build node-image ./kubernetes --arch linux/arm64 --base-image ghcr.io/${{ github.repository }}/base:${{ env.kind-version }} --image ghcr.io/${{ github.repository }}/node/arm64:${{ env.kubernetes-version }} --release
    - name: Build kind node-image
      run: crane index append -m ghcr.io/${{ github.repository }}/node/amd64:${{ env.kubernetes-version }} -m ghcr.io/${{ github.repository }}/node/arm64:${{ env.kubernetes-version }} -t ghcr.io/${{ github.repository }}/node:${{ env.kubernetes-version }}
    - run: crane ghcr.io/${{ github.repository }}/node:${{ env.kubernetes-version }} kind-node.tar
